// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Loja.Migrations
{
	[GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class inicio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inicio));
        
        string IMigrationMetadata.Id
        {
            get { return "201808092340061_inicio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
